style fixes

diff --git a/bin/rlaunch b/bin/rlaunch
--- a/bin/rlaunch
+++ b/bin/rlaunch
@@ -1,4 +1,6 @@
 #!/bin/bash
+#
+# Submit a job to process multiple subjects and runs.
 
 if [ $# -lt 1 ]; then
     cat <<EOF
@@ -67,23 +69,27 @@ ids=true
 jobname=Job
 while getopts ":f:n:tJ:g" opt; do
     case $opt in
-	t)
-	    test=true
-	    ;;
-	f)
-	    runifexist=true
-	    file="$OPTARG"
-	    ;;
-	n)
-	    runifmissing=true
-	    file="$OPTARG"
-	    ;;
-	J)
-	    jobname="$OPTARG"
-	    ;;
-	g)
-	    ids=false
-	    ;;
+        t)
+            test=true
+            ;;
+        f)
+            runifexist=true
+            file="$OPTARG"
+            ;;
+        n)
+            runifmissing=true
+            file="$OPTARG"
+            ;;
+        J)
+            jobname="$OPTARG"
+            ;;
+        g)
+            ids=false
+            ;;
+        *)
+            echo "Invalid option: $opt"
+            exit 1
+            ;;
     esac
 done
 shift $((OPTIND-1))
@@ -94,21 +100,21 @@ runids="$3"
 shift 3
 
 args="-ni"
-if [ $runifexist = true ]; then
+if [[ $runifexist = true ]]; then
     args="$args -f $file"
-elif [ $runifmissing = true ]; then
+elif [[ $runifmissing = true ]]; then
     args="$args -m $file"
 fi
 
-if [ $ids = true ]; then
+if [[ $ids = true ]]; then
     subjects="$subjnos"
 else
     subjects=$(subjids $subjnos)
 fi
 
-if [ -z "$BATCHDIR" ]; then
+if [[ ! $BATCHDIR ]]; then
     export BATCHDIR=$PWD
-elif [ ! -d "$BATCHDIR" ]; then
+elif [[ ! -d $BATCHDIR ]]; then
     echo "Error: BATCHDIR does not exist: $BATCHDIR"
     exit 1
 fi
@@ -116,23 +122,23 @@ fi
 # determine file to write commands to
 jobfile=$(get_auto_jobfile.sh "$jobname")
 
-if [ $test = true ]; then
+if [[ $test = true ]]; then
     run_runs.sh $args "$command" "$runids" "$subjects"
 else
-    run_runs.sh $args "$command" "$runids" "$subjects" > $jobfile
+    run_runs.sh $args "$command" "$runids" "$subjects" > "$jobfile"
 fi
 
 if [ $test = true ]; then
     exit 1
 fi
 
-cat $jobfile
-chmod +x $jobfile
+cat "$jobfile"
+chmod +x "$jobfile"
 
 # set the output file and sbatch file to standard names
-file=$(basename $jobfile)
-name=$(echo $file | cut -d . -f 1)
-outfile=$BATCHDIR/${name}.out
-batchfile=$BATCHDIR/${name}.slurm
+file=$(basename "$jobfile")
+name=$(echo "$file" | cut -d . -f 1)
+outfile="$BATCHDIR/${name}.out"
+batchfile="$BATCHDIR/${name}.slurm"
 
-launch -s $jobfile -J $name -o $outfile -f $batchfile -k "$@"
+launch -s "$jobfile" -J "$name" -o "$outfile" -f "$batchfile" -k "$@"
diff --git a/bin/slaunch b/bin/slaunch
--- a/bin/slaunch
+++ b/bin/slaunch
@@ -1,4 +1,6 @@
 #!/bin/bash
+#
+# Submit a job to process multiple subjects.
 
 if [ $# -lt 2 ]; then
     cat <<EOF
@@ -74,26 +76,30 @@ jobname=Job
 verbose=1
 while getopts ":f:n:tJ:gq" opt; do
     case $opt in
-	t)
-	    test=true
-	    ;;
-	f)
-	    runifexist=true
-	    file="$OPTARG"
-	    ;;
-	n)
-	    runifmissing=true
-	    file="$OPTARG"
-	    ;;
-	J)
-	    jobname="$OPTARG"
-	    ;;
-	g)
-	    ids=false
-	    ;;
-	q)
-	    verbose=0
-	    ;;
+        t)
+            test=true
+            ;;
+        f)
+            runifexist=true
+            file="$OPTARG"
+            ;;
+        n)
+            runifmissing=true
+            file="$OPTARG"
+            ;;
+        J)
+            jobname="$OPTARG"
+            ;;
+        g)
+            ids=false
+            ;;
+        q)
+            verbose=0
+            ;;
+        *)
+            echo "Invalid option: $opt"
+            exit 1
+            ;;
     esac
 done
 shift $((OPTIND-1))
@@ -102,11 +108,11 @@ command="$1"
 nos="$2"
 shift 2
 
-nos=$(echo $nos | sed "s/:/ /g")
+nos=${nos//:/ }
 
-if [ -z "$BATCHDIR" ]; then
+if [[ ! $BATCHDIR ]]; then
     export BATCHDIR=$PWD
-elif [ ! -d "$BATCHDIR" ]; then
+elif [[ ! -d $BATCHDIR ]]; then
     echo "Error: BATCHDIR does not exist: $BATCHDIR"
     exit 1
 fi
@@ -117,29 +123,29 @@ jobfile=$(get_auto_jobfile.sh "$jobname")
 for no in $nos; do
     # get the subject identifier
     if [ $ids = true ]; then
-	subject=$no
+        subject="$no"
     else
-	subject=$(subjids $no)
+        subject=$(subjids "$no")
     fi
 
     if [ $runifexist = true ]; then
-	# check for a dependency file
-	subj_file=$(echo "$file" | sed s/{}/$subject/g)
-	if [ ! -a "$subj_file" ]; then
-	    if [ $verbose -gt 0 ]; then
-	       echo "Missing file: $subj_file"
-	    fi
-	    continue
-	fi
+        # check for a dependency file
+        subj_file=${file//\{\}/$subject}
+        if [ ! -a "$subj_file" ]; then
+            if [ $verbose -gt 0 ]; then
+               echo "Missing file: $subj_file"
+            fi
+            continue
+        fi
     elif [ $runifmissing = true ]; then
-	# check for a missing output file
-	subj_file=$(echo "$file" | sed s/{}/$subject/g)
-	if [ -a "$subj_file" ]; then
-	    if [ $verbose -gt 0 ]; then
-		echo "File exists: $subj_file"
-	    fi
-	    continue
-	fi
+        # check for a missing output file
+        subj_file=${file//\{\}/$subject}
+        if [ -a "$subj_file" ]; then
+            if [ $verbose -gt 0 ]; then
+                echo "File exists: $subj_file"
+            fi
+            continue
+        fi
     fi
     
     # fill in subject ID and split commands
@@ -147,7 +153,7 @@ for no in $nos; do
     echo "$subj_command"
     
     if [ $test = false ]; then
-	echo -e "$subj_command" >> $jobfile
+        echo -e "$subj_command" >> $jobfile
     fi
 done
 
diff --git a/bin/subjids b/bin/subjids
--- a/bin/subjids
+++ b/bin/subjids
@@ -18,8 +18,8 @@ fi
 
 if [ -u $SUBJIDFORMAT ]; then
     if [ -u $STUDY ]; then
-	echo "STUDY and SUBJIDFORMAT are unset; quitting."
-	exit 1
+        echo "STUDY and SUBJIDFORMAT are unset; quitting."
+        exit 1
     fi
 
     # default format: $STUDY_XX
@@ -29,9 +29,13 @@ fi
 sep=":"
 while getopts ":s:" opt; do
     case $opt in
-	s)
-	    sep="$OPTARG"
-	    ;;
+        s)
+            sep="$OPTARG"
+            ;;
+        *)
+            echo "Invalid option: $opt"
+            exit 1
+            ;;
     esac
 done
 shift $((OPTIND-1))
@@ -41,9 +45,9 @@ subjids=""
 for no in $nos; do
     subject=$(printf "$SUBJIDFORMAT" $no)
     if [ -z "$subjids" ]; then
-	subjids="$subject"
+        subjids="$subject"
     else
-	subjids="${subjids}${sep}${subject}"
+        subjids="${subjids}${sep}${subject}"
     fi
 done
 echo "$subjids"
